#!/usr/bin/env bash

CONKY_DIR="${HOME}/.conky"

#########################################################################################
# Put the command that launches the conky configuration file that uses this script here #
#########################################################################################
weather_conky_launch_command="conky -b"


#####################################
# Put your Accuweather address here #
#####################################
#address="https://www.accuweather.com/en/ar/buenos-aires/7894/weather-forecast/7894"
address="https://www.accuweather.com/en/us/hutto/78634/weather-forecast/2110192"
#address="https://www.accuweather.com/en/gr/kastoria/178682/weather-forecast/178682"
#address="https://www.accuweather.com/en/de/lichtenstein/09350/weather-forecast/171261"
#address="https://www.accuweather.com/en/aq/casey-station/2273690/weather-forecast/2273690"

#Pause weather conky
pkill -STOP -xf "$weather_conky_launch_command"

# Make the temp directories as needed
  [ -d $CONKY_DIR/Accuweather_conky_script/temp ] || mkdir $CONKY_DIR/Accuweather_conky_script/temp
  [ -d $CONKY_DIR/Accuweather_conky_script/temp/images ] || mkdir $CONKY_DIR/Accuweather_conky_script/temp/images
  [ -d $CONKY_DIR/Accuweather_conky_script/temp/images_hourly ] || mkdir $CONKY_DIR/Accuweather_conky_script/temp/images_hourly

#function: test_image
test_image () {
    case $1 in
         1)
           echo a
         ;;
         2|3)
           echo b
         ;;
         4|5)
           echo c
         ;;
         6)
           echo d
         ;;
         7)
           echo e
         ;;
         8)
           echo f
         ;;
         11)
           echo 0
         ;;
         12)
           echo h
         ;;
         13|14)
           echo g
         ;;
         15)
           echo m
         ;;
         16|17)
           echo k
         ;;
         18)
           echo i
         ;;
         19)
           echo q
         ;;
         20|21|23)
           echo o
         ;;
         22)
           echo r
         ;;
         24|31)
           echo E
         ;;
         25)
           echo v
         ;;
         26)
           echo x
         ;;
         29)
           echo y
         ;;
         30)
           echo 5
         ;;
         32)
           echo 6
         ;;
         33)
           echo A
         ;;
         34|35)
           echo B
         ;;
         36|37)
           echo C
         ;;
         38)
           echo D
         ;;
         39|40)
           echo G
         ;;
         41|42)
           echo K
         ;;
         43|44)
           echo O
         ;;
         *)
	   echo -
		 ;;
	esac
	}


	#function: test_wind
	test_wind () {
	    case $1 in
	         CLM)
	           echo \-
	         ;;
	         S)
	           echo 1
	         ;;
	         SSW)
	           echo 2
	         ;;
	         SW)
	           echo 3
	         ;;
	         WSW)
	           echo 4
	         ;;
	         W)
	           echo 5
	         ;;
	         WNW)
	           echo 6
	         ;;
	         NW)
	           echo 7
	         ;;
	         NNW)
	           echo 8
	         ;;
	         N)
	           echo 9
	         ;;
	         NNE)
	           echo \:
	         ;;
	         NE)
	           echo \;
	         ;;
	         ENE)
	           echo \<
	         ;;
	         E)
	           echo \=
	         ;;
	         ESE)
	           echo \>
	         ;;
	         SE)
	           echo \?
	         ;;
	         SSE)
	           echo \@
	         ;;
	    esac
	}


############################
# Check the user arguments #
############################

if (( $# < 1 || $# > 18 )); then
	echo "Invalid arguments!"
	exit
fi

forecast0=0
forecast2015=0
forecast2016=0
hourly0=0
hourly2015=0
hourly2016=0
h_24hours=1
h_real=1
h_uv=1
h_wind=1
h_wind_g=1
h_hum=1
h_ind_hum=1
h_dew=1
h_cl_cov=1
h_prec_am=1
h_visib=1
h_cl_ceil=1

for i in $*
	do
		if [[ $i != -f && $i != -f2015 && $i != -f2016 && $i != -h && $i != -h2015 && $i != -h2016 && $i != -h_12h && $i != -h_no_real && $i != -h_no_uv && $i != -h_no_wind && $i != -h_no_wind_g && $i != -h_no_hum && $i != -h_no_ind_hum && $i != -h_no_dew && $i != -h_no_cl_cov && $i != -h_no_prec_am && $i != -h_no_visib && $i != -h_no_cl_ceil ]]; then
			echo "Invalid arguments!"
			exit
		fi
		case $i in
			-f)
				forecast0=1
			;;
			-f2015)
				forecast2015=1
			;;
			-f2016)
				forecast2016=1
			;;
			-h)
				hourly0=1
			;;
			-h2015)
				hourly2015=1
			;;
			-h2016)
				hourly2016=1
			;;
			-h_12h)
				h_24hours=0
			;;
			-h_no_real)
				h_real=0
			;;
			-h_no_uv)
				h_uv=0
			;;
			-h_no_wind)
				h_wind=0
			;;
			-h_no_wind_g)
				h_wind_g=0
			;;
			-h_no_hum)
				h_hum=0
			;;
			-h_no_ind_hum)
				h_ind_hum=0
			;;
			-h_no_dew)
				h_dew=0
			;;
			-h_no_cl_cov)
				h_cl_cov=0
			;;
			-h_no_prec_am)
				h_prec_am=0
			;;
			-h_no_visib)
				h_visib=0
			;;
			-h_no_cl_ceil)
				h_cl_ceil=0
			;;
		esac
	done

if [[ $forecast0 == 1 ]]; then
	forecast2015=0
	forecast2016=0
fi
if [[ $hourly0 == 1 ]]; then
	hourly2015=0
	hourly2016=0
fi


last_number=$(echo $address|sed 's/^.*\///')


#############################################################
# NORMAL FORECAST: -f, -f2015 or -f2016 passed as arguments #
#############################################################
if [[ $forecast0 == 1 || $forecast2015 == 1 || $forecast2016 == 1 ]]; then

	#function: convert_time
	convert_time ()
	{
		hours=$(echo $1|awk -F ":| " '{print $1}')
		minutes=$(echo $1|awk -F ":| " '{print $2}')
		am_or_pm=$(echo $1|awk -F ":| " '{print $3}')
		if [[ $am_or_pm == "" ]]; then
			echo $1
			return 0
		elif [[ $am_or_pm == AM ]]; then
			if (( $hours < 10 )); then
				hours_24=0$hours
			fi
			if (( $hours == 10 || $hours == 11 )); then
				hours_24=$hours
			fi
			if (( $hours == 12 )); then
				hours_24=00
			fi
		elif [[ $am_or_pm == PM ]]; then
			if (( $hours != 12 )); then
				hours_24=$((hours+12))
			fi
			if (( $hours == 12 )); then
				hours_24=12
			fi
		fi
		time_24=$hours_24:$minutes
		if [[ $1 != "N/A" ]]; then
			echo $time_24
		elif [[ $1 == "N/A" ]]; then
			echo "N/A"
		fi
	}

sleep 0.2
	curr_addr="$(echo $address|sed 's/weather-forecast.*$//')"current-weather/"$last_number"
	curl -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -o $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_raw "$curr_addr"

	daily_addr="$(echo $address|sed 's/weather-forecast.*$//')"daily-weather-forecast/"$last_number"
	curl -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -o $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast_raw "$daily_addr"

##### del image forecast
	if [[ $forecast2015 == 1 ]]; then
	  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_*.png ]]; then
		rm $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_*.png
	  fi
	fi
	if [[ $forecast2016 == 1 ]]; then
	  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_*.png ]]; then
		rm $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_*.png
	  fi
	fi

sleep 0.2

	#current conditions
	if [[ -s $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_raw ]]; then

		sed '/current-weather-card/,/glacier-ad /!d' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_raw > $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp

sed -i '/div class=\"label-tooltip\" data-js/,/div class=\"current-weather-details/d' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp
		sed -i -e 's/\.svg.*$//g' -e 's/<\/div>//g' -e 's/<div>//g' -e 's/<\/span>//g' -e 's/<span class.*$//g' -e 's/^[\t]*//g' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp
		sed -i -e 's/.*weathericons\///' -e 's/^.*>//g' -e 's/&#xB0;.*$//g' -e 's/.*RealFeel&#xAE; //g' -e '/RealFeel Shade™/,+1d' -e '/Indoor Humidity/,+1d' -e '/^$/d' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp
#
		sed -i '1s/^0//' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp

# temporary file to control
#
cp $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_control_point


		if [[ $(sed -n 5p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp) != 'Max UV Index' ]]; then
			sed -i "5s/^/Max UV\n0\n/" $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp
		fi


		wind_dir=$(sed -n 8p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp|head -c 1)
		if [[ $wind_dir == 0 ]]; then
			sed -i '8s/^/CLM /' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp
		fi

		sed -i '8s/ /\n/1' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp


		sed '/sunrise-sunset card-module content-module/,/temp-history content-module/!d' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_raw > $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1

		sed -i -e 's/.*"text-value">//g' -e 's/<\/span>$//g' -e '/</d' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1
#
		sed -i -e '1d;4d' -e 's/^[\t]*//g' -e 's/ AM/:AM/g' -e 's/ PM/:PM/g' -e 's/ .*$//g' -e '/^$/d' -e 's/:AM/ AM/g' -e 's/:PM/ PM/g' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1

		sed -i -e '1N;s/\n/:/' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1

		if [[ $(sed -n 4p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1) != "N/A" && $(sed -n 5p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1) != "N/A" && $(sed -n 6p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1) != "N/A" && $(sed -n 7p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1) != "N/A" ]]; then

			sed -i '4N;s/\n/:/' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1
		fi


# sorting  сортировка
# curr_cond line 1,2 номер изобр. облака и температуры сейчас , number icon and Temperature now
		sed -n 1,2p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp > $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 3 температура ощущение  Real Feel
		sed -n 4p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 4 облачность  Forecast
		sed -n 3p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 5 направление ветра  Wind Direction
		sed -n 8p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 6 скорость ветра  Wind Speed
#
		sed -n 9p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 7 влажность Humidity
		sed -n 13p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 8 давление  Pressure
		sed -n 17p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 9 УФ индекс  UV Index
		sed -n 6p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 10 облачность  Cloud Cover
		sed -n 19p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 11 влажность  Indoor Humidity (for compatibility with old config file)
		sed -n 13p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 12 точка росы  Dew Point
		sed -n 15p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 13 видимость  Visibility
		sed -n 21p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 14,15 солнце  рассвет, закат  Sun Rise Sun Set
		sed -n 2,3p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1 >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 16 солнце длит.  Sunlight Duration
		sed -n 1p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1 >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 17 порывы ветра  Wind Gusts
		sed -n 11p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 18,19 луна  восход, заход  Moon Rise Moon Set
		sed -n 5,6p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1 >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 20   Moonlight Duration
		sed -n 4p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1 >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 21 высота облаков  Cloud Ceiling
		sed -n 23p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 22 	#convert Image Number curr. cond.  to  Weather font letter curr. cond.
	    image=$(sed -n 1p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond)
	    echo $(test_image $image) >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond
# curr_cond line 23   Sun Rise-24h
		sunrise_time=$(sed -n 14p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond)
		echo $(convert_time "$sunrise_time") >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 24  Sun Set-24h
		sunrise_time=$(sed -n 15p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond)
		echo $(convert_time "$sunrise_time") >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 25  Moon Rise-24h
		sunrise_time=$(sed -n 18p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond)
		echo $(convert_time "$sunrise_time") >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

# curr_cond line 26  Moon Set-24h
		sunrise_time=$(sed -n 19p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond)
		echo $(convert_time "$sunrise_time") >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond


## curr_cond line 27   convert Wind Direction curr. cond.  to  Wind font letter curr. cond.
		wind=$(sed -n 5p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond)
		echo $(test_wind $wind) >> $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

	if (( $(sed -n 14p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond|wc -c) == 8 )); then
			sed -i '14s/^/0/' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond
		fi
		if (( $(sed -n 15p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond|wc -c) == 8 )); then
			sed -i '15s/^/0/' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond
		fi
		if (( $(sed -n 18p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond|wc -c) == 8 )); then
			sed -i '18s/^/0/' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond
		fi
		if (( $(sed -n 19p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond|wc -c) == 8 )); then
			sed -i '19s/^/0/' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond
	fi

sleep 0.2

# Copy image clouds

	    if [[ $forecast2015 == 1 ]]; then
			cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2015/$(sed -n 1p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond).png $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_0.png
			cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2015/$(sed -n 5p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond).png $CONKY_DIR/Accuweather_conky_script/temp/images/wind_0.png
		fi
		if [[ $forecast2016 == 1 ]]; then
			cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2016/$(sed -n 1p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond).png $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_0.png
			cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2016/$(sed -n 5p $CONKY_DIR/Accuweather_conky_script/temp/curr_cond).png $CONKY_DIR/Accuweather_conky_script/temp/images/wind_0.png
		fi
	fi


## delete tendency pressure
#		sed -i '8s/^.*; //' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond

## tendency pressure
#
	sed -i -e '8s/&#x2194;/↔/g' -e '8s/&#x2191;/↑/g' -e '8s/&#x2193;/↓/g' -e '8s/&#x2197;/↗/g' -e '8s/&#x2198;/↘/g' -e '8s/&#x219D;/↝/g' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond


########## location, time update
		sed '/header-loc-weather">\|<p class="sub">/!d' $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_raw > $CONKY_DIR/Accuweather_conky_script/temp/location
		sed -i -e 's/^.*">//g' -e 's/<\/div>.*$//g' -e 's/<\/p>.*$//g' -e 's/,/ /' $CONKY_DIR/Accuweather_conky_script/temp/location

############


	#Daily forecast
	if [[ -s $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast_raw ]]; then

		sed '/<div class="daily-wrapper" data-qa="dailyCard0">/,/Further Ahead/!d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast_raw > $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

		sed -i '/<div class="daily-wintercast-cta">/,/div class="daily-wrapper"/d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

		sed -i -e 's/\.svg.*$//g' -e 's/&#xB0;<\/span>//g' -e 's/<\/span>//g' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

		sed -i -e 's/^.*">\///' -e 's/^.*">//' -e 's/.*weathericons\///g' -e 's/^[\t]*//g' -e '/^$/d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

		sed -i -e '/<\|>\|fill=\|^[ ]*$\|Further Ahead/d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

		sed -i '/WinterCast/,+1d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

        sed -i '/connatixEl/,+2d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

        sed -i '/}/,+1d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

		sed -i '85,$d' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast
#
# Change a short name to a long one or translate into another language
#		sed -i -e 's/^Sun$/Sunday/g' -e 's/^Mon$/Monday/g' -e 's/^Tue$/Tuesday/g' -e 's/^Wed$/Wednesday/g' -e 's/^Thu$/Thursday/g' -e 's/^Fri$/Friday/g' -e 's/^Sat$/Saturday/g' $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast

sleep 0.2
# Copy image clouds

		for (( i=1; i<=21; i+=1 ))
		  do
	          echo >> $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast
		  done
		for (( i=3; i<=80; i+=7 ))
		  do
	          image=$(sed -n "${i}"p $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast)
	          echo $(test_image $image) >> $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast
		  done
		if [[ $forecast0 == 0 ]]; then
			j=1
			for (( i=3; i<=80; i+=7 ))
			  do
				if [[ $forecast2015 == 1 ]]; then
					cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2015/$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast).png $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_$j.png
				fi
				if [[ $forecast2016 == 1 ]]; then
					cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2016/$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast).png $CONKY_DIR/Accuweather_conky_script/temp/images/forecast_$j.png
				fi
				((j++))
			  done
		fi
	fi
fi

sleep 0.2
#############################################################
# HOURLY FORECAST: -h, -h2015 or -h2016 passed as arguments #
#############################################################
#function: convert_time_h
	convert_time_h ()
	{
		hours=$(echo $1|awk -F ":| " '{print $1}')
		am_or_pm=$(echo $1|awk -F ":| " '{print $2}')
		if [[ $am_or_pm == "" ]]; then
			echo $1
			return 0
		elif [[ $am_or_pm == AM ]]; then
			if (( $hours < 10 )); then
				hours_24=0$hours
			fi
			if (( $hours == 10 || $hours == 11 )); then
				hours_24=$hours
			fi
			if (( $hours == 12 )); then
				hours_24=00
			fi
		elif [[ $am_or_pm == PM ]]; then
			if (( $hours != 12 )); then
				hours_24=$((hours+12))
			fi
			if (( $hours == 12 )); then
				hours_24=12
			fi
		fi
		time_24=$hours_24:00
		echo $time_24
	}

if [[ $hourly0 == 1 || $hourly2015 == 1 || $hourly2016 == 1 ]]; then

	#Hourly: 24h

	hourly_addr1="$(echo $address|sed 's/weather-forecast.*$//')"hourly-weather-forecast/"$last_number"
	hourly_addr2="$(echo $address|sed 's/weather-forecast.*$//')"hourly-weather-forecast/"$last_number"?day=2

	curl -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -o $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw1 "$hourly_addr1"

	curl -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Connection: keep-alive' -H 'Upgrade-Insecure-Requests: 1' -H 'Cache-Control: max-age=0' -o $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw2 "$hourly_addr2"

	if [[ -s $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw1 && -s $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw2 ]]; then

		cat $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw1 $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw2 > $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw_temp

	sed '/<div class=\"hourly-wrapper content-module\">/,/day=/!d' $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw_temp > $CONKY_DIR/Accuweather_conky_script/temp/hourly



#		#Hourly file
#
	sed -i '/div class=\"label-tooltip\" data-js=/,/div class=\"hourly-content-container/d' $CONKY_DIR/Accuweather_conky_script/temp/hourly

#remove spaces and tabs in lines
#		sed -i -e 's/^[ \|\t]*//g' $CONKY_DIR/Accuweather_conky_script/temp/hourly

		sed -i '/div class=\"real-feel-mobile/,/<\/div>/d' $CONKY_DIR/Accuweather_conky_script/temp/hourly

#Поменять &#xAE;  на  <span class="value">space
		sed -i -e 's/&#xAE;/<span class="value">space/g' $CONKY_DIR/Accuweather_conky_script/temp/hourly
		# и  к   space присоединить следующую строку(удалив space и \n- новая строка)
		sed -i -z 's/space\n//g' $CONKY_DIR/Accuweather_conky_script/temp/hourly

		sed -i '/Indoor Humidity\|Air Quality\|RealFeel Shade\|RealFeel Guide\|Ice/d' $CONKY_DIR/Accuweather_conky_script/temp/hourly

#
	sed -i '/class="date"\|weathericons\/\|temp metric\|RealFeel<span\|"phrase"\|Max UV Index\|Wind\|Wind Gusts\|Humidity\|Dew Point\|Cloud Cover\|Visibility\|Cloud Ceiling/!d' $CONKY_DIR/Accuweather_conky_script/temp/hourly

##adding empty lines for compatibility with the old config. file
#date
		sed -i -e 's/<\/span><\/h2>/\n--/g' $CONKY_DIR/Accuweather_conky_script/temp/hourly

		sed -i -e 's/<\/span>.*$//g' -e 's/\.svg.*$//g' -e 's/<\/div>.*$//g' -e 's/<span class="value">/\n/g' $CONKY_DIR/Accuweather_conky_script/temp/hourly

		sed -i -e 's/.*weathericons\///g' -e 's/^.*>//g' -e 's/&#xB0;.*$//g' -e 's/&#xAE;//g' -e 's/^[ \|\t]*//g' $CONKY_DIR/Accuweather_conky_script/temp/hourly


		#Populate Max UV and Prec. Amount values where needed
		i=1
		while IFS= read -r line;
			do
				if [[ $(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly) == Wind ]]; then
					j=$((i-2))
					if [[ $(sed -n ${j}p $CONKY_DIR/Accuweather_conky_script/temp/hourly) != 'Max UV Index' ]]; then
						sed -i "${i}s/^/Max UV Index\n0\n/" $CONKY_DIR/Accuweather_conky_script/temp/hourly
						((i+=3))
					fi
				elif [[ $(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly) == Visibility ]]; then
					j=$((i-2))
					if [[ $(sed -n ${j}p $CONKY_DIR/Accuweather_conky_script/temp/hourly) != 'Rain' && $(sed -n ${j}p $CONKY_DIR/Accuweather_conky_script/temp/hourly) != 'Snow' ]]; then
						sed -i "${i}s/^/Prec. Amount\n-\n/" $CONKY_DIR/Accuweather_conky_script/temp/hourly
						((i+=3))
					fi
				fi
			((i+=1))
			done < $CONKY_DIR/Accuweather_conky_script/temp/hourly

		sed -i '/^$/d' $CONKY_DIR/Accuweather_conky_script/temp/hourly

##adding empty lines for compatibility with the old config. file
	sed -i '/Dew Point/i Indoor Hum.\n0' $CONKY_DIR/Accuweather_conky_script/temp/hourly
	sed -i '/Max UV Index/i precip\n-\nNot' $CONKY_DIR/Accuweather_conky_script/temp/hourly


		sed -i '/^Further Ahead$/d' $CONKY_DIR/Accuweather_conky_script/temp/hourly
		sed -i '721,$d' $CONKY_DIR/Accuweather_conky_script/temp/hourly
		sed -i -e 's/ mph$\| km\/h$//g' -e 's/°.*$//g' $CONKY_DIR/Accuweather_conky_script/temp/hourly


##### del image hourly
	if [[ $hourly2015 == 1 ]]; then
	  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/images_hourly/hourly_*.png ]]; then
		rm $CONKY_DIR/Accuweather_conky_script/temp/images_hourly/hourly_*.png
	  fi
	fi
	if [[ $hourly2016 == 1 ]]; then
	  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/images_hourly/hourly_*.png ]]; then
		rm $CONKY_DIR/Accuweather_conky_script/temp/images_hourly/hourly_*.png
	  fi
	fi


#	# Convert number image hourly  to  Weather font letter. Copy image clouds
		for (( i=3; i<=720; i+=30 ))
		  do
		image=$(sed -n "${i}"p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
		echo $(test_image $image) >> $CONKY_DIR/Accuweather_conky_script/temp/hourly
			  sed -i "$(( i+9 ))s/ .*$//" $CONKY_DIR/Accuweather_conky_script/temp/hourly
			  sed -i "$(( i+17 ))s/ .*$//" $CONKY_DIR/Accuweather_conky_script/temp/hourly
		  done
		if [[ $hourly0 == 0 ]]; then
			j=1
			for (( i=3; i<=720; i+=30 ))
			  do
		    	if [[ $hourly2015 == 1 ]]; then
					cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2015/$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly).png $CONKY_DIR/Accuweather_conky_script/temp/images_hourly/hourly_$j.png
				fi
				if [[ $hourly2016 == 1 ]]; then
					cp $CONKY_DIR/Accuweather_conky_script/Forecast_Images_2016/$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly).png $CONKY_DIR/Accuweather_conky_script/temp/images_hourly/hourly_$j.png
				fi
		    	((j++))
			  done
		fi
	fi

	# Convert times in hourly from am/pm to freedom times
	for (( i=1; i<=720; i+=30 ))
		  do
		   h=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			  sed -i ${i}s/^.*$/$(convert_time_h "$h")/ $CONKY_DIR/Accuweather_conky_script/temp/hourly
#	# Add times in hourly  :0    ru version
#		  sed -i ${i}s/^.*$/"$h":00/ $CONKY_DIR/Accuweather_conky_script/temp/hourly
		  done
sleep 0.2
	##convert Wind Direction hourly  to  Wind font letter hourly
		echo 'Font letter wind  hourly ' >> $CONKY_DIR/Accuweather_conky_script/temp/hourly
			j=1
		for (( i=14; i<=720; i+=30 ))
		  do
		   wind=$(sed -n "${i}"p $CONKY_DIR/Accuweather_conky_script/temp/hourly | awk '{print $1}')
		   echo $(test_wind $wind) >> $CONKY_DIR/Accuweather_conky_script/temp/hourly

			((j++))
		  done



##############################################################
	# Full info, next 24h - altogether24 file

#
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/altogether24 ]]; then
#
	rm $CONKY_DIR/Accuweather_conky_script/temp/altogether24
#
  fi
#
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015 ]]; then
#
	rm $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
#
  fi
#
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016 ]]; then
#
	rm $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
#
  fi


	#TIME
	echo "\${color1}TIME\${goto 100}$(sed -n 1p $CONKY_DIR/Accuweather_conky_script/temp/hourly)" > $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=160
	for (( i=31; i<=360; i+=30 ))
		do
			time=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "1s/$/\${goto $jump_to}$time/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=361; i<=720; i+=30 ))
			do
				time=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "1s/$/\${goto $jump_to}$time/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	sed -i '1s/$/\n\n\n/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24

	#FORECAST
	echo "\${color1}FORECAST\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=7; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly|awk '{print $1}'|cut -c1-8)
			sed -i "5s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=367; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly|awk '{print $1}'|cut -c1-8)
				sed -i "5s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi
	sed -i '5s/$/\n/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=7; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly|awk '{print $2}'|cut -c1-8)
			sed -i "6s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=367; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly|awk '{print $2}'|cut -c1-8)
				sed -i "6s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#TEMPERATURE
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "TEMPER.\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=4; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "8s/$/\${goto $jump_to}$messg°/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=364; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "8s/$/\${goto $jump_to}$messg°/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#REAL FEEL
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "REAL FEEL\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=6; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "10s/$/\${goto $jump_to}$messg°/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=366; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "10s/$/\${goto $jump_to}$messg°/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#CHANCE OF PRECIPITATION
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "PRECIP. %\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=9; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "12s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=369; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "12s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#MAX UV INDEX
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "UV INDEX\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=12; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "14s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=372; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "14s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#WIND
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "WIND\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=14; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "16s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=374; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "16s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#WIND GUSTS
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "WIND GUSTS\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=16; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "18s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=376; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "18s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#HUMIDITY
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "HUMIDITY\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=18; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "20s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=378; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "20s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#INDOOR HUMIDITY
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "IND. HUMID.\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=20; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "22s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=380; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "22s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#DEW POINT
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "DEW POINT\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=22; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "24s/$/\${goto $jump_to}$messg°/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=382; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "24s/$/\${goto $jump_to}$messg°/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#CLOUD COVER
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "CLOUD CVR\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=24; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "26s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=384; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "26s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#PRECIPITATION AMOUNT
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "PREC. AM.\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=26; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "28s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=386; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "28s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#VISIBILITY
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "VISIBILITY\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=28; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "30s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=388; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "30s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#CLOUD CEILING
	echo "\${color1}\${goto 100}\${hr 1}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	echo "CLOUD CEIL.\${color}" >> $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	jump_to=100
	for (( i=30; i<=360; i+=30 ))
		do
			messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
			sed -i "32s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=390; i<=720; i+=30 ))
			do
				messg=$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)
				sed -i "32s/$/\${goto $jump_to}$messg/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
	fi

	#IMAGES
	if [[ $hourly0 == 0 ]]; then
		if [[ $hourly2015 == 1 ]]; then
					jump_to=75
					cp $CONKY_DIR/Accuweather_conky_script/temp/altogether24 $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		fi
		if [[ $hourly2016 == 1 ]]; then
					jump_to=85
					cp $CONKY_DIR/Accuweather_conky_script/temp/altogether24 $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
#  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/altogether24 ]]; then
#		rm $CONKY_DIR/Accuweather_conky_script/temp/altogether24
#  fi
		hours=$((12+$h_24hours*12))
		for (( i=1; i<=$hours; i+=1 ))
			do
				if [[ $hourly2015 == 1 ]]; then
					sed -i "4s/$/\${image \$HOME\/Accuweather_conky_script\/hourly_2015\/hourly_$i.png -s 60x36 -p $jump_to,49}/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
				fi
				if [[ $hourly2016 == 1 ]]; then
					sed -i "4s/$/\${image \$HOME\/Accuweather_conky_script\/hourly_2016\/hourly_$i.png -s 36x36 -p $jump_to,49}/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
				fi
				((jump_to+=60))
			done
	fi

	#CONKYFONT
	if [[ $hourly0 == 1 ]]; then
		sed -i '4s/$/\${color}\${font conkyweather:size=35}/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		jump_to=95
		for (( i=721; i<=732; i+=1 ))
			do
				sed -i "4s/$/\${goto $jump_to}$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
				((jump_to+=60))
			done
		if [[ $h_24hours == 1 ]]; then
			for (( i=733; i<=744; i+=1 ))
				do
					sed -i "4s/$/\${goto $jump_to}$(sed -n ${i}p $CONKY_DIR/Accuweather_conky_script/temp/hourly)/" $CONKY_DIR/Accuweather_conky_script/temp/altogether24
					((jump_to+=60))
				done
		fi
		sed -i '4s/$/\${font}/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		sed -i '2,3d' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
	fi

	#DELETE UNWANTED VARIABLES
	if [[ $h_real == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '7,8s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '9,10s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '9,10s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_uv == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '11,12s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '13,14s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '13,14s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_wind == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '13,14s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '15,16s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '15,16s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_wind_g == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '15,16s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '17,18s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '17,18s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi


	if [[ $h_hum == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '17,18s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '19,20s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '19,20s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi


	if [[ $h_ind_hum == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '19,20s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '21,22s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '21,22s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_dew == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '21,22s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '23,24s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '23,24s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_cl_cov == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '23,24s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '25,26s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '25,26s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_prec_am == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '25,26s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '27,28s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '27,28s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_visib == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '27,28s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '29,30s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '29,30s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

	if [[ $h_cl_ceil == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '29,30s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '31,32s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '31,32s/^.*$/VOID/' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
		fi
	fi

  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/altogether24 ]]; then
	sed -i '/VOID/d' $CONKY_DIR/Accuweather_conky_script/temp/altogether24
  fi
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015 ]]; then
	sed -i '/VOID/d' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2015
  fi
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016 ]]; then
	sed -i '/VOID/d' $CONKY_DIR/Accuweather_conky_script/temp/altogether24_2016
  fi



fi

sleep 0.5

##################################################################
#del. temp files

#
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp ]]; then
#
	rm $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp
#
  fi
#
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1 ]]; then
#
	rm $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_temp1
#
  fi
#  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_control_point ]]; then
#	rm $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_control_point
#  fi

#
  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw_temp ]]; then
#
	rm $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw_temp
#
  fi

###############################################################
#del. raw files

#  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_raw ]]; then
#	rm $CONKY_DIR/Accuweather_conky_script/temp/curr_cond_raw
#  fi
#  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast_raw ]]; then
#	rm $CONKY_DIR/Accuweather_conky_script/temp/daily_forecast_raw
#  fi
#  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw1 ]]; then
#	rm $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw1
#  fi
#  if [[ -f $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw2 ]]; then
#	rm $CONKY_DIR/Accuweather_conky_script/temp/hourly_raw2
#  fi
#

##################################################################


#Resume weather conky
pkill -CONT -xf "$weather_conky_launch_command"
