#!/usr/bin/env bash

#########################################################################################
# Put the command that launches the conky configuration file that uses this script here #
#########################################################################################
weather_conky_launch_command="conky -b"


#####################################
# Put your Accuweather address here #
#####################################
#address="http://www.accuweather.com/en/ar/buenos-aires/7894/weather-forecast/7894"
#address="https://www.accuweather.com/en/us/hutto-tx/78634/weather-forecast/2110192"
address="http://www.accuweather.com/en/gr/kastoria/178682/weather-forecast/178682"
#address="http://www.accuweather.com/en/de/lichtenstein/09350/weather-forecast/171261"


#Pause weather conky
pkill -STOP -xf "$weather_conky_launch_command"

#function: test_image
test_image () {
    case $1 in
         1)
           echo a
         ;;
         2|3)
           echo b
         ;;
         4|5)
           echo c
         ;;
         6)
           echo d
         ;;
         7)
           echo e
         ;;
         8)
           echo f
         ;;
         11)
           echo 0
         ;;
         12)
           echo h
         ;;
         13|14)
           echo g
         ;;
         15)
           echo m
         ;;
         16|17)
           echo k
         ;;
         18)
           echo i
         ;;
         19)
           echo q
         ;;
         20|21|23)
           echo o
         ;;
         22)
           echo r
         ;;
         24|31)
           echo E
         ;;
         25)
           echo v
         ;;
         26)
           echo x
         ;;
         29)
           echo y
         ;;
         30)
           echo 5
         ;;
         32)
           echo 6
         ;;
         33)
           echo A
         ;;
         34|35)
           echo B
         ;;
         36|37)
           echo C
         ;;
         38)
           echo D
         ;;
         39|40)
           echo G
         ;;
         41|42)
           echo K
         ;;
         43|44)
           echo O
         ;;
         *)
		   echo -
		 ;;
        esac
}


############################
# Check the user arguments #
############################

if (( $# < 1 || $# > 15 )); then
	echo "Invalid arguments!"
	exit
fi

forecast0=0
forecast2015=0
forecast2016=0
hourly0=0
hourly2015=0
hourly2016=0
h_24hours=1
h_real=1
h_wind=1
h_rain=1
h_snow=1
h_ice=1
h_uv=1
h_cloud=1
h_humid=1
h_dew=1
h_visib=1

for i in $*
	do
		if [[ $i != -f && $i != -f2015 && $i != -f2016 && $i != -h && $i != -h2015 && $i != -h2016 && $i != -h_12h && $i != -h_no_real && $i != -h_no_wind && $i != -h_no_rain && $i != -h_no_snow && $i != -h_no_ice && $i != -h_no_uv && $i != -h_no_cloud && $i != -h_no_humid && $i != -h_no_dew && $i != -h_no_visib ]]; then
			echo "Invalid arguments!"
			exit
		fi
		case $i in
			-f)
				forecast0=1
			;;
			-f2015)
				forecast2015=1
			;;
			-f2016)
				forecast2016=1
			;;
			-h)
				hourly0=1
			;;
			-h2015)
				hourly2015=1
			;;
			-h2016)
				hourly2016=1
			;;
			-h_12h)
				h_24hours=0
			;;
			-h_no_real)
				h_real=0
			;;
			-h_no_wind)
				h_wind=0
			;;
			-h_no_rain)
				h_rain=0
			;;
			-h_no_snow)
				h_snow=0
			;;
			-h_no_ice)
				h_ice=0
			;;
			-h_no_uv)
				h_uv=0
			;;
			-h_no_cloud)
				h_cloud=0
			;;
			-h_no_humid)
				h_humid=0
			;;
			-h_no_dew)
				h_dew=0
			;;
			-h_no_visib)
				h_visib=0
			;;
		esac
	done

if [[ $forecast0 == 1 ]]; then
	forecast2015=0
	forecast2016=0
fi
if [[ $hourly0 == 1 ]]; then
	hourly2015=0
	hourly2016=0
fi


last_number=$(echo $address|sed 's/^.*\///')


#############################################################
# NORMAL FORECAST: -f, -f2015 or -f2016 passed as arguments #
#############################################################
if [[ $forecast0 == 1 || $forecast2015 == 1 || $forecast2016 == 1 ]]; then

	#function: convert_time
	convert_time ()
	{
		hours=$(echo $1|awk -F ":| " '{print $1}')
		minutes=$(echo $1|awk -F ":| " '{print $2}')
		am_or_pm=$(echo $1|awk -F ":| " '{print $3}')
		if [[ $am_or_pm == AM ]]; then
			if (( $hours < 10 )); then
				hours_24=0$hours
			fi
			if (( $hours == 10 || $hours == 11 )); then
				hours_24=$hours
			fi
			if (( $hours == 12 )); then
				hours_24=00
			fi
		elif [[ $am_or_pm == PM ]]; then
			if (( $hours != 12 )); then
				hours_24=$((hours+12))
			fi
			if (( $hours == 12 )); then
				hours_24=12
			fi
		fi
		time_24=$hours_24:$minutes
		echo $time_24
	}

	#function: test_wind
	test_wind () {
	    case $1 in
	         CLM)
	           echo -
	         ;;
	         S)
	           echo 1
	         ;;
	         SSW)
	           echo 2
	         ;;
	         SW)
	           echo 3
	         ;;
	         WSW)
	           echo 4
	         ;;
	         W)
	           echo 5
	         ;;
	         WNW)
	           echo 6
	         ;;
	         NW)
	           echo 7
	         ;;
	         NNW)
	           echo 8
	         ;;
	         N)
	           echo 9
	         ;;
	         NNE)
	           echo :
	         ;;
	         NE)
	           echo ;
	         ;;
	         ENE)
	           echo \<
	         ;;
	         E)
	           echo =
	         ;;
	         ESE)
	           echo \>
	         ;;
	         SE)
	           echo ?
	         ;;
	         SSE)
	           echo @
	         ;;
	    esac
	}

	curr_addr="$(echo $address|sed 's/weather-forecast.*$//')"current-weather/"$last_number"
	wget -U "Oh hi Mark!" -O $HOME/Accuweather_conky_script/curr_cond_raw "$curr_addr"

	daily_addr="$(echo $address|sed 's/weather-forecast.*$//')"daily-weather-forecast/"$last_number"
	wget -U "Oh hi Mark!" -O $HOME/Accuweather_conky_script/daily_forecast "$daily_addr"

	if [[ $forecast2015 == 1 ]]; then
		rm $HOME/Accuweather_conky_script/forecast_2015/forecast_*.png
	fi
	if [[ $forecast2016 == 1 ]]; then
		rm $HOME/Accuweather_conky_script/forecast_2016/forecast_*.png
	fi

	#current conditions
	if [[ -s $HOME/Accuweather_conky_script/curr_cond_raw ]]; then
		sed -i '/var sunMoon\|var curCon/!d' $HOME/Accuweather_conky_script/curr_cond_raw
		sed -i -e 's/^.*extended":{"//' -e 's/^.*moon":{"//' -e 's/,/:/g' -e 's/{"category.*value":/"/' -e 's/}:/":/g' -e 's/icon":/icon":"/' -e 's/:"now/":"now/' -e 's/"};//' -e 's/windDeg":/windDeg":"/' -e 's/°//g' -e 's/":"sun":{/:/' -e 's/"}};//' $HOME/Accuweather_conky_script/curr_cond_raw
		awk 'FNR==2 { print $38 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw > $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $46 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $44 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $42 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $34 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw|awk '{ print $3 }' >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $34 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw|awk '{ print $1, $2 }' >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $10 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $26 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $30 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $4 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $2 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $6 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==2 { print $32 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==1 { print $10 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==1 { print $12 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==1 { print $8 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		echo 'EMPTY LINE FOR COMPATIBILITY WITH THE OLD CONKYRC FILES' >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==1 { print $4 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==1 { print $6 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		awk 'FNR==1 { print $2 }' FS="\":\"" $HOME/Accuweather_conky_script/curr_cond_raw >> $HOME/Accuweather_conky_script/curr_cond
		echo 'EMPTY LINE FOR COMPATIBILITY WITH THE OLD CONKYRC FILES' >> $HOME/Accuweather_conky_script/curr_cond

	    image=$(sed -n 1p $HOME/Accuweather_conky_script/curr_cond)
	    echo $(test_image $image) >> $HOME/Accuweather_conky_script/curr_cond
		sunrise_time=$(sed -n 14p $HOME/Accuweather_conky_script/curr_cond)
		echo $(convert_time "$sunrise_time") >> $HOME/Accuweather_conky_script/curr_cond
		sunrise_time=$(sed -n 15p $HOME/Accuweather_conky_script/curr_cond)
		echo $(convert_time "$sunrise_time") >> $HOME/Accuweather_conky_script/curr_cond
		sunrise_time=$(sed -n 18p $HOME/Accuweather_conky_script/curr_cond)
		echo $(convert_time "$sunrise_time") >> $HOME/Accuweather_conky_script/curr_cond
		sunrise_time=$(sed -n 19p $HOME/Accuweather_conky_script/curr_cond)
		echo $(convert_time "$sunrise_time") >> $HOME/Accuweather_conky_script/curr_cond
		wind=$(sed -n 5p $HOME/Accuweather_conky_script/curr_cond)
		echo $(test_wind $wind) >> $HOME/Accuweather_conky_script/curr_cond
        if (( $(sed -n 14p /$HOME/Accuweather_conky_script/curr_cond|wc -c) == 8 )); then
			sed -i '14s/^/0/' $HOME/Accuweather_conky_script/curr_cond
		fi
		if (( $(sed -n 15p /$HOME/Accuweather_conky_script/curr_cond|wc -c) == 8 )); then
			sed -i '15s/^/0/' $HOME/Accuweather_conky_script/curr_cond
		fi
		if (( $(sed -n 18p /$HOME/Accuweather_conky_script/curr_cond|wc -c) == 8 )); then
			sed -i '18s/^/0/' $HOME/Accuweather_conky_script/curr_cond
		fi
		if (( $(sed -n 19p /$HOME/Accuweather_conky_script/curr_cond|wc -c) == 8 )); then
			sed -i '19s/^/0/' $HOME/Accuweather_conky_script/curr_cond
		fi
	    if [[ $forecast2015 == 1 ]]; then
			cp $HOME/Accuweather_conky_script/Forecast_Images_2015/$(sed -n 1p $HOME/Accuweather_conky_script/curr_cond).png $HOME/Accuweather_conky_script/forecast_2015/forecast_0.png
			cp $HOME/Accuweather_conky_script/Forecast_Images_2015/$(sed -n 5p $HOME/Accuweather_conky_script/curr_cond).png $HOME/Accuweather_conky_script/forecast_2015/wind_0.png
		fi
		if [[ $forecast2016 == 1 ]]; then
			cp $HOME/Accuweather_conky_script/Forecast_Images_2016/$(sed -n 1p $HOME/Accuweather_conky_script/curr_cond).png $HOME/Accuweather_conky_script/forecast_2016/forecast_0.png
			cp $HOME/Accuweather_conky_script/Forecast_Images_2016/$(sed -n 5p $HOME/Accuweather_conky_script/curr_cond).png $HOME/Accuweather_conky_script/forecast_2016/wind_0.png
		fi
	fi

	#Daily forecast
	if [[ -s $HOME/Accuweather_conky_script/daily_forecast ]]; then
		sed -i '/var dailyForecast/!d' $HOME/Accuweather_conky_script/daily_forecast
		sed -i -e 's/var dailyForecast = \[//' -e 's/","\|":"/\n/g' -e 's/icon":/icon\n/g' -e 's/,"phrase/\nphrase/g' -e 's/temp":/temp\n/g' -e 's/},"dow/\ndow/g' -e 's/":{"dTemp/\ndTemp/g' $HOME/Accuweather_conky_script/daily_forecast
		sed -i -e 's/}}.*,"date/\ndate/' -e 's/}}];//g' -e '1s/^.*$/date/' -e 's/°//g' $HOME/Accuweather_conky_script/daily_forecast
	    sed -i '601,$d' $HOME/Accuweather_conky_script/daily_forecast
	    for (( i=9; i<=569; i+=40 ))
		  do
	          image=$(sed -n "${i}"p $HOME/Accuweather_conky_script/daily_forecast)
	          echo $(test_image $image) >> $HOME/Accuweather_conky_script/daily_forecast
		  done
		for (( i=30; i<=590; i+=40 ))
		  do
	          image=$(sed -n "${i}"p $HOME/Accuweather_conky_script/daily_forecast)
	          echo $(test_image $image) >> $HOME/Accuweather_conky_script/daily_forecast
		  done
		if [[ $forecast0 == 0 ]]; then
			j=1
			for (( i=9; i<=569; i+=40 ))
			  do
				if [[ $forecast2015 == 1 ]]; then
					cp $HOME/Accuweather_conky_script/Forecast_Images_2015/$(sed -n ${i}p $HOME/Accuweather_conky_script/daily_forecast).png $HOME/Accuweather_conky_script/forecast_2015/forecast_$j.png
				fi
				if [[ $forecast2016 == 1 ]]; then
					cp $HOME/Accuweather_conky_script/Forecast_Images_2016/$(sed -n ${i}p $HOME/Accuweather_conky_script/daily_forecast).png $HOME/Accuweather_conky_script/forecast_2016/forecast_$j.png
				fi
				((j++))
			  done
			for (( i=30; i<=590; i+=40 ))
			  do
				if [[ $forecast2015 == 1 ]]; then
					cp $HOME/Accuweather_conky_script/Forecast_Images_2015/$(sed -n ${i}p $HOME/Accuweather_conky_script/daily_forecast).png $HOME/Accuweather_conky_script/forecast_2015/forecast_$j.png
				fi
				if [[ $forecast2016 == 1 ]]; then
					cp $HOME/Accuweather_conky_script/Forecast_Images_2016/$(sed -n ${i}p $HOME/Accuweather_conky_script/daily_forecast).png $HOME/Accuweather_conky_script/forecast_2016/forecast_$j.png
				fi
				((j++))
			  done
		fi
	fi
fi


#############################################################
# HOURLY FORECAST: -h, -h2015 or -h2016 passed as arguments #
#############################################################

if [[ $hourly0 == 1 || $hourly2015 == 1 || $hourly2016 == 1 ]]; then

	#Hourly: 24h

	if [[ $hourly2015 == 1 ]]; then
		rm $HOME/Accuweather_conky_script/hourly_2015/hourly_*.png
	fi
	if [[ $hourly2016 == 1 ]]; then
		rm $HOME/Accuweather_conky_script/hourly_2016/hourly_*.png
	fi

	hourly_addr1="$(echo $address|sed 's/weather-forecast.*$//')"hourly-weather-forecast/"$last_number"
	hourly_addr2="$(echo $address|sed 's/weather-forecast.*$//')"hourly-weather-forecast/"$last_number"?day=2
	wget -U "Oh hi Mark!" -O $HOME/Accuweather_conky_script/hourly_raw1 "$hourly_addr1"
	wget -U "Oh hi Mark!" -O $HOME/Accuweather_conky_script/hourly_raw2 "$hourly_addr2"

	if [[ -s $HOME/Accuweather_conky_script/hourly_raw1 && -s $HOME/Accuweather_conky_script/hourly_raw2 ]]; then
		sed -i '/var hourlyForecast/!d' $HOME/Accuweather_conky_script/hourly_raw1
		sed -i -e 's/var hourlyForecast = \[//' -e 's/","\|":"/\n/g' $HOME/Accuweather_conky_script/hourly_raw1
		sed -i -e 's/°.*ceiling/\nceiling/g' -e 's/{"extended":{"//' -e 's/":{"category//g' $HOME/Accuweather_conky_script/hourly_raw1
		sed -i -e 's/":\|},"/\n/g' -e 's/,"localDate/\nlocaldate/g' -e 's/"}];//g' -e 's/°//g' -e 's/ km\/h\| mph//g' $HOME/Accuweather_conky_script/hourly_raw1

		sed -i '/var hourlyForecast/!d' $HOME/Accuweather_conky_script/hourly_raw2
		sed -i -e 's/var hourlyForecast = \[//' -e 's/","\|":"/\n/g' $HOME/Accuweather_conky_script/hourly_raw2
		sed -i -e 's/°.*ceiling/\nceiling/g' -e 's/{"extended":{"//' -e 's/":{"category//g' $HOME/Accuweather_conky_script/hourly_raw2
		sed -i -e 's/":\|},"/\n/g' -e 's/,"localDate/\nlocaldate/g' -e 's/"}];//g' -e 's/°//g' -e 's/ km\/h\| mph//g' $HOME/Accuweather_conky_script/hourly_raw2

		cat $HOME/Accuweather_conky_script/hourly_raw1 $HOME/Accuweather_conky_script/hourly_raw2 > $HOME/Accuweather_conky_script/hourly
		sed -i '961,$d' $HOME/Accuweather_conky_script/hourly

		for (( i=28; i<=948; i+=40 ))
		  do
	          image=$(sed -n "${i}"p $HOME/Accuweather_conky_script/hourly)
	          echo $(test_image $image) >> $HOME/Accuweather_conky_script/hourly
		  done
		if [[ $hourly0 == 0 ]]; then
			j=1
			for (( i=28; i<=948; i+=40 ))
			  do
		    	if [[ $hourly2015 == 1 ]]; then
					cp $HOME/Accuweather_conky_script/Forecast_Images_2015/$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly).png $HOME/Accuweather_conky_script/hourly_2015/hourly_$j.png
				fi
				if [[ $hourly2016 == 1 ]]; then
					cp $HOME/Accuweather_conky_script/Forecast_Images_2016/$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly).png $HOME/Accuweather_conky_script/hourly_2016/hourly_$j.png
				fi
		    	((j++))
			  done
		fi
	fi


	# Full info, next 24h - altogether24 file
	rm $HOME/Accuweather_conky_script/{altogether24,altogether24_2015,altogether24_2016}

	#TIME
	echo "\${color1}TIME\${goto 100}$(sed -n 32p $HOME/Accuweather_conky_script/hourly)" > $HOME/Accuweather_conky_script/altogether24
	jump_to=160
	for (( i=72; i<=472; i+=40 ))
		do
			time=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "1s/$/\${goto $jump_to}$time/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=512; i<=952; i+=40 ))
			do
				time=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "1s/$/\${goto $jump_to}$time/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	sed -i '1s/$/\n\n\n/' $HOME/Accuweather_conky_script/altogether24

	#FORECAST
	echo "\${color1}FORECAST\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=34; i<=474; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly|awk '{print $1}'|cut -c1-8)
			sed -i "5s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=514; i<=954; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly|awk '{print $1}'|cut -c1-8)
				sed -i "5s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi
	sed -i '5s/$/\n/' $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=34; i<=474; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly|awk '{print $2}'|cut -c1-8)
			sed -i "6s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=514; i<=954; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly|awk '{print $2}'|cut -c1-8)
				sed -i "6s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#TEMPERATURE
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "TEMPER.\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=40; i<=480; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "8s/$/\${goto $jump_to}$messg°/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=520; i<=960; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "8s/$/\${goto $jump_to}$messg°/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#REAL FEEL
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "REAL FEEL\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=38; i<=478; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "10s/$/\${goto $jump_to}$messg°/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=518; i<=958; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "10s/$/\${goto $jump_to}$messg°/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#WIND
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "WIND\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=24; i<=464; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "12s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=504; i<=944; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "12s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#RAIN
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "RAIN\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=14; i<=454; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "14s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=494; i<=934; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "14s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#SNOW
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "SNOW\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=16; i<=456; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "16s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=496; i<=936; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "16s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#ICE
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "ICE\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=12; i<=452; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "18s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=492; i<=932; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "18s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#UV INDEX
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "UV INDEX\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=20; i<=460; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "20s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=500; i<=940; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "20s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#CLOUD COVER
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "CLOUD COV.\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=4; i<=444; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "22s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=484; i<=924; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "22s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#HUMIDITY
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "HUMIDITY\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=10; i<=450; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "24s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=490; i<=930; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "24s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#DEW POINT
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "DEW POINT\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=6; i<=446; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "26s/$/\${goto $jump_to}$messg°/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=486; i<=926; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "26s/$/\${goto $jump_to}$messg°/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#VISIBILITY
	echo "\${color1}\${goto 100}\${hr 1}" >> $HOME/Accuweather_conky_script/altogether24
	echo "VISIBILITY\${color}" >> $HOME/Accuweather_conky_script/altogether24
	jump_to=100
	for (( i=22; i<=462; i+=40 ))
		do
			messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
			sed -i "28s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
			((jump_to+=60))
		done
	if [[ $h_24hours == 1 ]]; then
		for (( i=502; i<=942; i+=40 ))
			do
				messg=$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)
				sed -i "28s/$/\${goto $jump_to}$messg/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
	fi

	#IMAGES
	if [[ $hourly0 == 0 ]]; then
		if [[ $hourly2015 == 1 ]]; then
					jump_to=75
					cp $HOME/Accuweather_conky_script/altogether24 $HOME/Accuweather_conky_script/altogether24_2015
		fi
		if [[ $hourly2016 == 1 ]]; then
					jump_to=85
					cp $HOME/Accuweather_conky_script/altogether24 $HOME/Accuweather_conky_script/altogether24_2016
		fi
		rm $HOME/Accuweather_conky_script/altogether24
		hours=$((12+$h_24hours*12))
		for (( i=1; i<=$hours; i+=1 ))
			do
				if [[ $hourly2015 == 1 ]]; then
					sed -i "4s/$/\${image \$HOME\/Accuweather_conky_script\/hourly_2015\/hourly_$i.png -s 60x36 -p $jump_to,49}/" $HOME/Accuweather_conky_script/altogether24_2015
				fi
				if [[ $hourly2016 == 1 ]]; then
					sed -i "4s/$/\${image \$HOME\/Accuweather_conky_script\/hourly_2016\/hourly_$i.png -s 36x36 -p $jump_to,49}/" $HOME/Accuweather_conky_script/altogether24_2016
				fi
				((jump_to+=60))
			done
	fi

	#CONKYFONT
	if [[ $hourly0 == 1 ]]; then
		sed -i '4s/$/\${color}\${font conkyweather:size=35}/' $HOME/Accuweather_conky_script/altogether24
		jump_to=95
		for (( i=961; i<=972; i+=1 ))
			do
				sed -i "4s/$/\${goto $jump_to}$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)/" $HOME/Accuweather_conky_script/altogether24
				((jump_to+=60))
			done
		if [[ $h_24hours == 1 ]]; then
			for (( i=973; i<=984; i+=1 ))
				do
					sed -i "4s/$/\${goto $jump_to}$(sed -n ${i}p $HOME/Accuweather_conky_script/hourly)/" $HOME/Accuweather_conky_script/altogether24
					((jump_to+=60))
				done
		fi
		sed -i '4s/$/\${font}/' $HOME/Accuweather_conky_script/altogether24
		sed -i '2,3d' $HOME/Accuweather_conky_script/altogether24
	fi

	#DELETE UNWANTED VARIABLES
	if [[ $h_real == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '7,8s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '9,10s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '9,10s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	if [[ $h_wind == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '9,10s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '11,12s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '11,12s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	if [[ $h_rain == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '11,12s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '13,14s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '13,14s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	if [[ $h_snow == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '13,14s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '15,16s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '15,16s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi


	if [[ $h_ice == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '15,16s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '17,18s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '17,18s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi


	if [[ $h_uv == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '17,18s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '19,20s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '19,20s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	if [[ $h_cloud == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '19,20s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '21,22s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '21,22s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	if [[ $h_humid == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '21,22s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '23,24s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '23,24s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	if [[ $h_dew == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '23,24s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '25,26s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '25,26s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	if [[ $h_visib == 0 ]]; then
		if [[ $hourly0 == 1 ]]; then
			sed -i '25,26s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24
		elif [[ $hourly2015 == 1 ]]; then
			sed -i '27,28s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2015
		elif [[ $hourly2016 == 1 ]]; then
			sed -i '27,28s/^.*$/VOID/' $HOME/Accuweather_conky_script/altogether24_2016
		fi
	fi

	sed -i '/VOID/d' $HOME/Accuweather_conky_script/{altogether24,altogether24_2015,altogether24_2016}

fi

#Resume weather conky
pkill -CONT -xf "$weather_conky_launch_command"
